go:
  main: ./app.go
  builds:
    - goos: linux
      goarch: amd64
    - goos: linux
      goarch: arm64
    - goos: windows
      goarch: amd64
    - goos: windows
      goarch: arm64
    - goos: darwin
      goarch: amd64
    - goos: darwin
      goarch: arm64
artifact_name: radio-javan-downloader-{{ .OS }}-{{ if eq .Arch "amd64" }}amd{{ else }}{{ .Arch }}{{ end }}-v{{ .Version }}{{ if eq .OS "windows" }}.exe{{ end }}
